// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var ruleTableRow;
    ruleTableRow = function(profile, item) {
      return "<tr>\n<td>" + profile[item.select_index].name + "</td>\n<td>" + item.path + "</td>\n</tr>";
    };
    chrome.storage.sync.get('DBE_data', function(items) {
      var body, d, data, profile, _i, _len, _results;
      if ('DBE_data' in items) {
        console.log(items.DBE_data);
        data = items.DBE_data.data;
        profile = items.DBE_data.profile;
        body = $("#rules_table tbody");
        _results = [];
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          d = data[_i];
          _results.push(body.append(ruleTableRow(profile, d)));
        }
        return _results;
      }
    });
    $("#table-type").text(chrome.i18n.getMessage("extTypefiles"));
    return $("#table-directory").text(chrome.i18n.getMessage("extDirectory"));
  });

}).call(this);
